### ISSUE TITLE
原数组操作

### ISSUE THREAD

**Issue by supershutong** [sisterAn/JavaScript-Algorithms#68]
题目要求：
在第一个数组上直接操作修改，不开辟新得内存空间。

```js
var merge = function (nums1, m, nums2, n) {
  let len = m + n
  while (n > 0) {
    if (m === 0) {
      nums1.splice(0, n, ...nums2.slice(0, n))
      break
    }
    nums1[--len] = nums1[m - 1] > nums2[n - 1] ? nums1[--m] : nums2[--n]
  }
};
```

**Comment by sisterAn** [comment]
> 题目要求：
> 在第一个数组上直接操作修改，不开辟新得内存空间。
> 
> ```js
> var merge = function (nums1, m, nums2, n) {
>   let len = m + n
>   while (n > 0) {
>     if (m === 0) {
>       nums1.splice(0, n, ...nums2.slice(0, n))
>       break
>     }
>     nums1[--len] = nums1[m - 1] > nums2[n - 1] ? nums1[--m] : nums2[--n]
>   }
> };
> ```

这是？
