### ISSUE TITLE
#### 解答：使用Map

### ISSUE THREAD

**Issue by supershutong** [sisterAn/JavaScript-Algorithms#77]
#### 解答：使用Map

- 空间复杂度：O(n)

此处Map最多存储26个字母，空间复杂度应该是O(1)

**Comment by sisterAn** [comment]
> #### 解答：使用Map
> * 空间复杂度：O(n)
> 
> 此处Map最多存储26个字母，空间复杂度应该是O(1)

这是指哪道题目？
